language: python

addons:
  apt:
    packages:
    - sshpass

install:
  - ssh-keyscan -H $UPB_HOST 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts
  - source ./texlive_install.sh
  - pip install tqdm

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - cd lecture_slides
  - travis_wait 15 python build.py  # timeout after 15 mins

deploy:
  - provider: script
    skip_cleanup: true
    script: sshpass -e scp -r built/ $UPB_USER@$UPB_HOST:$UPB_DEPLOY_DIR > /dev/null
    on:
      branch: master

